name: Run display.js

on:
  workflow_dispatch:  # Manual run ke liye trigger

jobs:
  run-labour:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout karein
        uses: actions/checkout@v3
        with:
          submodules: false   # Submodules ko checkout mat karo

      - name: Remove submodule references (optional safeguard)
        run: |
          git submodule deinit -f --all || echo "No submodules to deinit"
          git rm -f --cached Nrega-sheduler || echo "No submodule to remove"
          git config -f .git/config --remove-section submodule.Nrega-sheduler || echo "No config section"

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run display.js
        run: |
          node display.js
