name: Run display.js

on:
  workflow_dispatch:

jobs:
  run-labour:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout karein
        uses: actions/checkout@v3
        with:
          submodules: false    # Yeh line add karein

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run display.js
        run: |
          node display.js
