name: Run labour.js

on:
  workflow_dispatch:   # Manually run karne ke liye

jobs:
  run-labour:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout karein
        uses: actions/checkout@v3

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run labour.js
        run: |
          node labour.js
