name: Run labour.js every minute

on:
  schedule:
    - cron: '* * * * *'     # Every 1 minute
  workflow_dispatch:         # Allow manual trigger

jobs:
  run-labour:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run labour.js
        run: node labour.js
